---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-secret
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgCLoT4s0+cyg6isYXIDBvgNeASnGS+cnc5hC4Ot0Lk7HK8JbtI5/Cdyzl26FvYBWSNkgV7gTjAxY0bJWEEYk2axGbMaDD0OHo+awjzw8lXeYFksLfCJ8ScuX9wXmJDJyT8L0di0vvJX9v9x26IniIDmnfH3nT2W2KE199OCOXLA+jX4Ri+TR8LRJWWUqo9bSMVAqELFqgpWBE55mAPxLnl00mL9Wp4v28++oOrYl0WmL77FfSO7yWP/RbRwTdrPK7kkdDfGeYdvQJju78/PVdul/sRki2fXf8iDjh3p45RTarz6OSZFNqvgntUn4vhUC6zk9tDOpedwWqjjnQjLfReL2LkWcbm1UK08bLAigHvmSEhn41n886rQW0UKDdSVe0QcuIl6WKgwtIQNCpDrJBE/4l4L4i1oEE43vkc3sP6IpnCsYdxGqiVxW2jeDbODPiBFzTv0pCCpWXV73GHL7pjRc77I1XhgEtGK65aVc+hU2RQ3l/Pn37c5f1EwmEOG0fawYebFLrkmt/vmwBY0o2a+DE0/80fPst19tNzyU0GYyyinvI26UX+drnUkgdihNjxUPzRKqPV7T2NHaYFgehkO0/iwSqnLtGklTB6LnGi+OVa/LRpC6iBoJ2YhursD/fvTuC9mbvh/h0WKV/rVCOA8RXC9Nw7ki1PqRFoKIrTATyXKVRdTvXXMd/N/8Xb5hGKj1VibF9NpbS7uRQ==
    STRIPE_API_KEY: AgCVnOr4DucaAGrY1xrjPEbQ9O3HssXJa0lra9/SjVN3zkj6YjhEKLkG7MZsglk6Rk7nNRbaUWAd3gFTBkmnHGwzqSvXKxEK6HUe0yRQhK1WqZpjRi/DJOY/4CdBSHZ8Lnxxxofo2bpAcUxqO1ScQrQbbkSQWvSkBD9qy19StN1f6dfP3tEOq7yi+KJ4iTTaea4mVnIBldS+I94UhvqSotD07hBpUmszykD/Y25tGuYucQjSqQod7/FdbXzOu/nzLgc3dmt9j+K7Sjgn8Yd4nhdq9MsIuRAsGddgHdv4xVXIsthFdRx0F4XlKgngWU5UfhBfDx4WvUJT+1AHSpJoZl7L6WgKnE59zxUl+s24v9fikl3ORrZ4dV60y1xp2VPMnq2lsihwMTFcS7xyrmGYgkWrQfc5Rm3SzAH7La9CtFnVRHwCx+on7uSURJdOpKkq6dfdi5Fu9oaG2fuSxUwezrF9EdmSD2q6ps7vahGxem76DCKt0vDhXHcLR65kEHXTbHQwb4g7f5BSTs5rtZFBZCy6F8qCG+aKPrnSbJE7wG90PvOd5aJq7h4EO59Mz2ko4NXV9P8rD1wqt2TJ6ICMiWnfzn9Dfd9f4VJtGPxHq8dfc+bqA7cFlqpHAI4R54aUyEALp35gLK4KjKJwAq+eEfQR9te3DcYF72NIr/k82b2gD4nSaczezb6DDGhmELIeK0G1+Z0ItbzIstXbfJCn
  template:
    metadata:
      creationTimestamp: null
      name: ledger-secret
      namespace: payments
    type: Opaque
