name: Secure CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

env:
  IMAGE_NAME: ghcr.io/anirudhn300/ledger-api

jobs:

  security-and-build:

    runs-on: ubuntu-latest

    steps:

    # -------------------------------
    # Checkout
    # -------------------------------
    - name: Checkout Repository
      uses: actions/checkout@v4


    # -------------------------------
    # Setup Python
    # -------------------------------
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"


    # -------------------------------
    # Install Dependencies
    # -------------------------------
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f app/requirements.txt ]; then
          pip install -r app/requirements.txt
        fi


    # -------------------------------
    # Semgrep SAST
    # -------------------------------
    - name: Install Semgrep
      run: pip install semgrep


    - name: Run Semgrep
      run: |
        semgrep \
        --config=p/security-audit \
        --config=p/python \
        --error


    # -------------------------------
    # Gitleaks Secret Scan
    # -------------------------------
    - name: Run Gitleaks
      uses: zricethezav/gitleaks-action@v2
      continue-on-error: true


    # -------------------------------
    # Trivy Filesystem Scan
    # -------------------------------
    - name: Trivy Filesystem Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: .
        format: table
        exit-code: 0


    # -------------------------------
    # Login GHCR
    # -------------------------------
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}


    # -------------------------------
    # Build Image
    # -------------------------------
    - name: Build Docker Image
      run: |
        docker build \
        -t $IMAGE_NAME:${{ github.sha }} \
        ./app


    # -------------------------------
    # Trivy Image Scan
    # -------------------------------
    - name: Trivy Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.IMAGE_NAME }}:${{ github.sha }}
        format: table
        exit-code: 0


    # -------------------------------
    # Push Image
    # -------------------------------
    - name: Push Docker Image
      run: |
        docker push $IMAGE_NAME:${{ github.sha }}


    # -------------------------------
    # Install Cosign
    # -------------------------------
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3


    # -------------------------------
    # Sign Image
    # -------------------------------
    - name: Sign Container Image
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      run: |

        echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key

        cosign sign \
        --yes \
        --key cosign.key \
        $IMAGE_NAME:${{ github.sha }}


    # -------------------------------
    # Get Digest From Registry
    # -------------------------------
    - name: Get Image Digest
      id: digest

      run: |

        DIGEST=$(docker buildx imagetools inspect \
        $IMAGE_NAME:${{ github.sha }} \
        --format '{{json .Manifest.Digest}}')

        echo "digest=$DIGEST" >> $GITHUB_OUTPUT


    # -------------------------------
    # SLSA Provenance
    # -------------------------------
    - name: Generate SLSA Provenance
      uses: actions/attest-build-provenance@v2

      with:
        subject-name: ${{ env.IMAGE_NAME }}

        subject-digest: ${{ steps.digest.outputs.digest }}

        push-to-registry: true


    # -------------------------------
    # Verify Cosign
    # -------------------------------
    - name: Verify Cosign Signature

      run: |

        echo "${{ secrets.COSIGN_PUBLIC_KEY }}" > cosign.pub

        cosign verify \
        --key cosign.pub \
        $IMAGE_NAME:${{ github.sha }}


    # -------------------------------
    # Complete
    # -------------------------------
    - name: Pipeline Completed
      run: |
        echo "✅ Secure CI Pipeline completed successfully"